//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Cart {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no;
		
		protected System.Web.UI.WebControls.Button addtocart;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no1;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no1;
		
		protected System.Web.UI.WebControls.Button removefromcart;
		
		protected System.Web.UI.WebControls.Button btn_makeOrder;
		
		protected System.Web.UI.WebControls.Button btn_myorder;
	}
}
