//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_usernamelog;
		
		protected System.Web.UI.WebControls.TextBox txt_usernamelog;
		
		protected System.Web.UI.WebControls.Label lbl_passwordlog;
		
		protected System.Web.UI.WebControls.TextBox txt_passwordlog;
		
		protected System.Web.UI.WebControls.Button btn_login;
		
		protected System.Web.UI.WebControls.Label lbl_username;
		
		protected System.Web.UI.WebControls.TextBox txt_username;
		
		protected System.Web.UI.WebControls.Label lbl_first_name;
		
		protected System.Web.UI.WebControls.TextBox txt_first_name;
		
		protected System.Web.UI.WebControls.Label lbl_last_name;
		
		protected System.Web.UI.WebControls.TextBox txt_last_name;
		
		protected System.Web.UI.WebControls.Label lbl_password;
		
		protected System.Web.UI.WebControls.TextBox txt_password;
		
		protected System.Web.UI.WebControls.Label lbl_email;
		
		protected System.Web.UI.WebControls.TextBox txt_email;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label lbl_usernamevend;
		
		protected System.Web.UI.WebControls.TextBox txt_usernamevend;
		
		protected System.Web.UI.WebControls.Label lbl_first_namevend;
		
		protected System.Web.UI.WebControls.TextBox txt_first_namevend;
		
		protected System.Web.UI.WebControls.Label lbl_last_namevend;
		
		protected System.Web.UI.WebControls.TextBox txt_last_namevend;
		
		protected System.Web.UI.WebControls.Label lbl_passwordvend;
		
		protected System.Web.UI.WebControls.TextBox txt_passwordvend;
		
		protected System.Web.UI.WebControls.Label lbl_emailvend;
		
		protected System.Web.UI.WebControls.TextBox txt_emailvend;
		
		protected System.Web.UI.WebControls.Label lbl_company_name;
		
		protected System.Web.UI.WebControls.TextBox txt_company_name;
		
		protected System.Web.UI.WebControls.Label lbl_bank_acc_no;
		
		protected System.Web.UI.WebControls.TextBox txt_bank_acc_no;
		
		protected System.Web.UI.WebControls.Button button2;
	}
}
