//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no;
		
		protected System.Web.UI.WebControls.Label lbl_product_name;
		
		protected System.Web.UI.WebControls.TextBox txt_product_name;
		
		protected System.Web.UI.WebControls.Label lbl_category;
		
		protected System.Web.UI.WebControls.TextBox txt_category;
		
		protected System.Web.UI.WebControls.Label lbl_product_description;
		
		protected System.Web.UI.WebControls.TextBox txt_product_description;
		
		protected System.Web.UI.WebControls.Label lbl_price;
		
		protected System.Web.UI.WebControls.TextBox txt_price;
		
		protected System.Web.UI.WebControls.Label lbl_color;
		
		protected System.Web.UI.WebControls.TextBox txt_color;
		
		protected System.Web.UI.WebControls.Button btn_EditProduct;
	}
}
