//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Hello_Customer {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_cust_mobil;
		
		protected System.Web.UI.WebControls.TextBox txt_cust_mobil;
		
		protected System.Web.UI.WebControls.Button btn_cust_mobile;
		
		protected System.Web.UI.WebControls.Button btn_products;
		
		protected System.Web.UI.WebControls.Button btn_GoToWishlist;
		
		protected System.Web.UI.WebControls.Button btn_cart;
		
		protected System.Web.UI.WebControls.Label lbl_number;
		
		protected System.Web.UI.WebControls.TextBox txt_number;
		
		protected System.Web.UI.WebControls.Label lbl_expiry_date;
		
		protected System.Web.UI.WebControls.TextBox txt_expiry_date;
		
		protected System.Web.UI.WebControls.Label lbl_cvv_code;
		
		protected System.Web.UI.WebControls.TextBox txt_cvv_code;
		
		protected System.Web.UI.WebControls.Button btn_ccr;
	}
}
