//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Hello_Admin {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_vendor_username;
		
		protected System.Web.UI.WebControls.TextBox txt_vendor_username;
		
		protected System.Web.UI.WebControls.Button btn_activate;
		
		protected System.Web.UI.WebControls.Label lbl_admin_mobile;
		
		protected System.Web.UI.WebControls.TextBox txt_admin_mobile;
		
		protected System.Web.UI.WebControls.Button btn_admin_mobile;
		
		protected System.Web.UI.WebControls.Button Orders;
		
		protected System.Web.UI.WebControls.Label lbl_order_no;
		
		protected System.Web.UI.WebControls.TextBox txt_order_no;
		
		protected System.Web.UI.WebControls.Button btn_update;
		
		protected System.Web.UI.WebControls.Button btn_toDeals;
	}
}
