//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class My_Orders {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_chooseCC;
		
		protected System.Web.UI.WebControls.TextBox txt_chooseCC;
		
		protected System.Web.UI.WebControls.Label lbl_order_no_forCC;
		
		protected System.Web.UI.WebControls.TextBox txt_order_no_forCC;
		
		protected System.Web.UI.WebControls.Button btn_chooseCC;
		
		protected System.Web.UI.WebControls.Label lbl_orderId;
		
		protected System.Web.UI.WebControls.TextBox txt_orderId;
		
		protected System.Web.UI.WebControls.Label lbl_cash_amount;
		
		protected System.Web.UI.WebControls.TextBox txt_cash_amount;
		
		protected System.Web.UI.WebControls.Label lbl_credit_amount;
		
		protected System.Web.UI.WebControls.TextBox txt_credit_amount;
		
		protected System.Web.UI.WebControls.Button btn_verify_Payment;
		
		protected System.Web.UI.WebControls.Label lbl_cancelOrder;
		
		protected System.Web.UI.WebControls.TextBox txt_cancel_order;
		
		protected System.Web.UI.WebControls.Button Cancel_order;
	}
}
