//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Offers {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button btn_checkOfferonProduct;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no;
		
		protected System.Web.UI.WebControls.Button btn_addOffer;
		
		protected System.Web.UI.WebControls.Label lbl_offeramount;
		
		protected System.Web.UI.WebControls.TextBox txt_offeramount;
		
		protected System.Web.UI.WebControls.Label lbl_expiry_date;
		
		protected System.Web.UI.WebControls.TextBox txt_expiry_date;
		
		protected System.Web.UI.WebControls.Button btn_applyOffer;
		
		protected System.Web.UI.WebControls.Label lbl_vendorname;
		
		protected System.Web.UI.WebControls.TextBox txt_vendorname;
		
		protected System.Web.UI.WebControls.Label lbl_offerid;
		
		protected System.Web.UI.WebControls.TextBox txt_offerid;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no2;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no2;
		
		protected System.Web.UI.WebControls.Button btn_checkandremoveExpiredOffer;
		
		protected System.Web.UI.WebControls.Label lbl_offerid2;
		
		protected System.Web.UI.WebControls.TextBox txt_offerid2;
	}
}
