//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidDBWebApp {
	
	
	public partial class Products {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label myText;
		
		protected System.Web.UI.WebControls.Button btn_editproduct;
		
		protected System.Web.UI.WebControls.Button btn_offers;
	}
}
