//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Today_s_Deals {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_deal_amount;
		
		protected System.Web.UI.WebControls.TextBox txt_deal_amount;
		
		protected System.Web.UI.WebControls.Label lbl_date;
		
		protected System.Web.UI.WebControls.TextBox txt_date;
		
		protected System.Web.UI.WebControls.Button btn_CreateDeals;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxaddDeal;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxserial_no;
		
		protected System.Web.UI.WebControls.Button Btn_Add_deal;
		
		protected System.Web.UI.WebControls.Label lbl_deal_id;
		
		protected System.Web.UI.WebControls.TextBox txt_deal_id;
		
		protected System.Web.UI.WebControls.Button Btn_remove_deal;
	}
}
