//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StupidBDWebApp {
	
	
	public partial class Wishlist {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lbl_name;
		
		protected System.Web.UI.WebControls.TextBox txt_name;
		
		protected System.Web.UI.WebControls.Button btn_createWishlist;
		
		protected System.Web.UI.WebControls.Label lbl_wish_name1;
		
		protected System.Web.UI.WebControls.TextBox txt_wish_name1;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no;
		
		protected System.Web.UI.WebControls.Button addtowish;
		
		protected System.Web.UI.WebControls.Label lbl_wish_name2;
		
		protected System.Web.UI.WebControls.TextBox txt_wish_name2;
		
		protected System.Web.UI.WebControls.Label lbl_serial_no2;
		
		protected System.Web.UI.WebControls.TextBox txt_serial_no2;
		
		protected System.Web.UI.WebControls.Button removefromwish;
	}
}
